--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetries-app
  namespace: tetris
spec:

  selector:
    matchLabels:
      app: tetries-app
  template:
    metadata:
      labels:
        app: tetries-app
    spec:
      containers:
        - name: tetries-app
          image: 865487342006.dkr.ecr.us-east-1.amazonaws.com/eks/tetries:sha-d779c47
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "214Mi"
            limits:
              cpu: "400m"
              memory: "456Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: tetries-service
spec:
  selector:
    app: tetries-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tetries-hpa
  namespace: tetris
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tetries-app
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60