--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetries-app
  namespace: tetris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetries-app
  template:
    metadata:
      labels:
        app: tetries-app
    spec:
      containers:
        - name: tetries-app
          image: 865487342006.dkr.ecr.us-east-1.amazonaws.com/eks/tetries:sha-fdced2d
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "300m"
              memory: "524Mi"
            limits:
              cpu: "700m"
              memory: "756Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: tetries-service
spec:
  selector:
    app: tetries-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer