apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetries-app
  namespace: tetries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetries-app
  template:
    metadata:
      labels:
        app: tetries-app
    spec:
      containers:
        - name: tetries-app
          image: 865487342006.dkr.ecr.us-east-1.amazonaws.com/eks/tetries:sha-9ef147b
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"