name: CI/CD

on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: eks/tetries
  IMAGE_NAME: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Running tests..."

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: debug jwt
        run: |
          TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          echo $TOKEN | cut -d. -f2 | base64 -d 2>/dev/null | jq .
      # ✅ Configure AWS credentials (OIDC recommended)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::865487342006:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      # ✅ Login to ECR
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # ✅ Extract metadata
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=sha,format=short

      # ✅ Build & Push to ECR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: Tetris-V2
          file: Tetris-V2/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: genetate  GitHub app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Verify token was generated
        run: |
          if [ -z "${{ steps.app-token.outputs.token }}" ]; then
            echo "========>   ${{ steps.app-token.outputs.token }}"
            echo "❌ Token is empty — app-token step failed"
            exit 1
          else
            echo "✅ Token generated successfully"
          fi
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: kambalaashok4/TetrisApp-Jenkins-EKS-ArgoCD-TF   # change this
          token: ${{ steps.app-token.outputs.token }}
           

      - name: Update image tag
        run: |
          IMAGE_TAG="${{ needs.build-and-push.outputs.image_tag }}"
          ECR_URI=865487342006.dkr.ecr.us-east-1.amazonaws.com/eks/tetries
          sed -i "s|image: .*|image: ${ECR_URI}:${IMAGE_TAG}|g"  k8s/deployment.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/kambalaashok4/TetrisApp-Jenkins-EKS-ArgoCD-TF.git
          git add k8s/deployment.yaml
          git commit -m "chore: update image tag to ${{ needs.build-and-push.outputs.image_tag }}"
          git push